version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "/src/node_modules"
          key: "npm_packages"
      - run: npm run lint     
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm run test 

workflows:
  adam_npm_workflow:
    jobs:
      - build
      - test
        requires:
        - build